name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            provider.yaml
          generate_release_notes: true
          draft: true
          prerelease: true

      - name: Update latest release
        run: |
          echo "Release ${{ github.ref_name }} created successfully"
          echo "Provider can now be installed with:"
          echo "devpod provider add ${{ github.repository }}"
